### PR TITLE
Reconfigure UI of Client App (Issue #30)

### LINKED ISSUE #30: UI design improvements
**Describe the solution you'd like**
We have a basic functional UI that allows users to see their upcoming shifts and sign up for new shifts. While the UI is functional, its look and usability need to be improved. Specifically:
1. The Volunteer Dashboard shows upcoming shifts and a few shelters that need volunteers to sign up in two columns. It seems that the user will be disoriented by this UI. Volunteer dashboard needs a clear call to action: what do we want the user to do when they land on that dashboard.
2. The mobile version of this UI is not usable (it's the same UI but on a smaller screen. The mobile version of the UI needs a different layout. Instead of the navigation menu across the top, it needs to have the standard mobile hamburger menu, where the user can select the page to navigate to. The layout of the mobile dashboard can't be in 3 columns, because there isn't enough screen size for that.
3. The UI needs to follow basic UI principles of: whitespace, alignment, contrast, scale, typography, color, and visual hierarchy (as described in the UI Design Fundamentals tutorial: https://scrimba.com/learn/design )

**Additional context**
Whoever works on this issue will need to work with the client to get his opinion on the UI changes.

### PR DESCRIPTION
**Pull request by loganwyas**
Fixes #30

**What was changed?**

We have changed the user interface of the client-side application.
* Dashboard is now responsive to the screen width
* Shift sign-up process allows users to change the selection
* User can select start and end time 
* User sees a confirmation page once shifts are submitted.
* User sees a call to action button on the mobile devices when they are on the dashboard.
* Navbar link names are clear and easy to understand.
* Colors are different for various shift types (green - upcoming, Mustard - previous shifts, light gray - unregistered shifts )
* Button text changed for better understanding

**Why was it changed?** 

This was changed because the user interface didn't look very nice, and we wanted to make it look better when giving it to our clients. 

**How was it changed?**

We went into the individual pages of the React app and modified the CSS to style everything differently and format it for mobile (using media queries to get the width of the screen)

**Next steps**

The Shift signup process is not yet completely responsive to the screen width. Will take this up as part of another story

**Screenshots that show the changes (if applicable):**

Dashboard:

image

Shift Signup page:

image

Confirmation Page:

image

### CODE REVIEW

**Comment by kate-holdener** [comment]
@AbhilashKotha That looks amazing and it's easy to sign up now. One suggestion I have is to move "Submit shifts" to the area where current selection is shown and make "Submit Shifts" bigger. Right now, "Submit shifts" is somewhat difficult to find (unless you know where it is). @loganwyas could you help with that, if you both agree on this change?

**Comment by loganwyas** [comment]
I will quickly add that change

**Comment by AbhilashKotha** [comment]
Thanks, @kate-holdener! it was in my plan but forgot by the time I finished all the other changes.  

@loganwyas You can also increase the height of the current selection div if you remove the footer.

**Review by kate-holdener — APPROVED** [review]
Looks good to me. The UI changes are great!

**Pull request merged**
