### PR TITLE
Implement Validations for Time Input, Overlapping Events, and Prevent Past Date Event Creation (#136) fixed

### LINKED ISSUE #136: Implement Validations for Time Input, Overlapping Events, and Prevent Past Date Event Creation
**Is this task related to a feature or a bug? Please include relevant issue numbers below.**
**Given** the current implementation of the "Request for Help" page,
**When** the user interacts with the calendar to select dates and times,
**Then** the time input allows submitting the form without providing a start and end time, the calendar permits overlapping events which might cause confusion, and it’s possible to create events for past dates, which ideally should be restricted to future dates for better planning.

**Describe the solution you'd like**
The following improvements should be made:

- Add validation to ensure that the form cannot be submitted when both the start and end times are left blank.
- Implement functionality to prevent overlapping events, ensuring that volunteers or events do not overlap in time slots.
- Restrict the creation of events for past dates and allow scheduling only for present or future dates.

Acceptance Criteria:

- [x] Validate time input to ensure that the form cannot be submitted when both the start and end times are left blank.
- [x] Prevent the creation of overlapping events.
- [x] Restrict event creation to future dates only.

### PR DESCRIPTION
**Pull request by tnhi26990**
Fixes #136 

**What was changed?**

I changed the Request for Help page.

**Why was it changed?**

It was changed because currently, users could select past dates to sign up for shifts and register for overlapping shifts. Additionally, there was no warning message for an empty start time or end time.

**How was it changed?**

I added conditions to check for overlapping shifts and if the user selected a past date. I made a new modal to display an error message for past dates. I also added some conditions to check if the required files are empty and to ensure that the number of volunteers required is always greater than 0. 

**Screenshots that show the changes (if applicable):**
Screenshot 2024-10-24 at 1 06 12 PM
Screenshot 2024-11-01 at 4 04 48 PM
Screenshot 2024-11-01 at 4 02 26 PM
Screenshot 2024-11-01 at 4 03 59 PM

### CODE REVIEW

**Comment by cbiddle3** [comment]
Currently, it allows you to make a shift with negative and 0 volunteers (it should not let them submit a shift like that), also it doesn't allow a user to enter any non-numeric characters except it allows e + and . (these should also not be able to be entered since the other characters cannot be). Also I think in some cases there could possibly intentionally be overlapping shifts (we can ask Tim), but I think when the box comes up to enter shift information they should be informed it overlaps and disable the submit button (for no overlapping shifts) (not when they click submit) otherwise if we do allow it they should have to check a box saying they know it overlaps. Again we can consult Tim about if there would ever be any overlapping shifts.

**Review by cbiddle3 — CHANGES_REQUESTED** [review]
Just requesting the logical changes in my previous comment.Currently, it allows you to make a shift with negative and 0 volunteers (it should not let them submit a shift like that), also it doesn't allow a user to enter any non-numeric characters except it allows e + and . (these should also not be able to be entered since the other characters cannot be). Also I think in some cases there could possibly intentionally be overlapping shifts (we can ask Tim), but I think when the box comes up to enter shift information they should be informed it overlaps and disable the submit button (for no overlapping shifts) (not when they click submit) otherwise if we do allow it they should have to check a box saying they know it overlaps. Again we can consult Tim about if there would ever be any overlapping shifts.

**Comment by tnhi26990** [comment]
> Just requesting the logical changes in my previous comment.Currently, it allows you to make a shift with negative and 0 volunteers (it should not let them submit a shift like that), also it doesn't allow a user to enter any non-numeric characters except it allows e + and . (these should also not be able to be entered since the other characters cannot be). Also I think in some cases there could possibly intentionally be overlapping shifts (we can ask Tim), but I think when the box comes up to enter shift information they should be informed it overlaps and disable the submit button (for no overlapping shifts) (not when they click submit) otherwise if we do allow it they should have to check a box saying they know it overlaps. Again we can consult Tim about if there would ever be any overlapping shifts.

I asked Tim about overlapped shifts, and he said there was no need for overlapping shifts.

**Review by Brijitha1609 — COMMENTED** [review]
Great job, @tnhi26990!! The code and functionalities look great overall.The only area that needs a slight adjustment is the alignment on the Agenda page. The event text seems slightly off or cut off, and fixing this minor alignment issue would make the page even more polished. Aside from this small detail, everything else is excellent!

**Review by Brijitha1609 — APPROVED** [review]
I've reviewed the changes, and everything looks perfect now. I'll go ahead and merge it. Excellent work!!

**Pull request merged**
