### PR TITLE
Connected to a real DB (Mongo)

### LINKED ISSUE #19: Connect server side app to a real database
**The problem**
Our current implementation of the server side application uses an [in-memory database](https://github.com/oss-slu/shelter_volunteers/blob/main/server/repository/memrepo.py), which is suitable for developing application functionality, but is not suitable for production. Production level solution will need to use a real database

**Describe the solution you'd like**
Add a module to the <code>server/repository</code> directory that implements the same functions as in MemRepo, but connecting and interacting with a real database. MongoDB is probably a good option here. The connection to the database should be parametrized. This can be done by following the example in chapters 6 and 7 of the [Clean Architectures in Python Second Edition](https://leanpub.com/clean-architectures-in-python)

### PR DESCRIPTION
**Pull request by AbhilashKotha**
Fixes #19 

What changed?
Added Mongo repo to handle database operations and a docker container setup for setting up the database. This will replace the current memrepo setup. 

How to see the changes: 
1. Setup database using detailed instructions available at https://github.com/oss-slu/shelter_volunteers/blob/ee8cd09dbac5ba210b6f59c24ba6159525807216/docker_files/docker_instructions.md 
2. Run server and front end as usual

### CODE REVIEW

**Comment by kate-holdener** [comment]
@AbhilashKotha Let me know when this is ready for a review

**Comment by AbhilashKotha** [comment]
@kate-holdener Sorry it is taking longer than expected. I will try to have the PR up by tomorrow morning.

**Review by kate-holdener — CHANGES_REQUESTED** [review]
@AbhilashKotha I tried this out and your solution works. Please add detailed instructions to the project-level README.md file on how to run the code. Other teammates might not be familiar with Docker, so please elaborate on the dependencies (docker must be installed), the order in which components need to be started up (db, then server, then client), etc.

**Comment by AbhilashKotha** [comment]
> then server, then client),

@kate-holdener I have now added instructions to the readme file.

**Review by kate-holdener — APPROVED** [review]

**Pull request merged**
