### PR TITLE
Signup process optimization for small screens

### LINKED ISSUE #46: Mobile view of "Sign up for shifts"
**Is this task related to a feature or a bug? Please include relevant issue numbers below.**
With the completion of issue #30, we have an improved UI and with the completion of issue #29, the volunteer sign-up experience is much improved. The volunteer sign-up page on small screen needs to be adjusted, as the area showing current selection overlaps the are where the user can pick facilities and shifts.

Screenshot 2023-11-06 at 3 03 46 PM

**Describe the solution you'd like**
@AbhilashKotha shared the following prototype for improving the mobile "sign up for shifts" page.

https://github.com/oss-slu/shelter_volunteers/assets/42073871/3c0e1649-87fe-4261-925b-6de62d0f937e

### PR DESCRIPTION
**Pull request by AbhilashKotha**
Fixes #46 

**What was changed?**

* The UI of the shift signup process looks on mobile devices or small screens has been updated
* The list has less white space (Made the changes as per client's feedback)
* **Bug fix:** Previously, when a user tried to remove an entry from the current selection, it used to remove the last row irrespective of the user's selection (due to a mistake in code). It is now fixed.
* **Fix:** User can now only select from the date and time picker and cannot manually input any date (Manual input was allowing past times)

**Why was it changed?**

* To make it easy for the users to use our application on small screens

**How was it changed?**

* Majorly by altering CSS files and some minor changes in the JS components.

**Screenshots that show the changes (if applicable):**

image

image

image

### CODE REVIEW

**Review by kate-holdener — CHANGES_REQUESTED** [review]
Here are some problems I found on different simulated screen sizes:
Screen Shot 2023-11-15 at 1 39 54 PM

Screen Shot 2023-11-15 at 1 40 17 PM

Screen Shot 2023-11-15 at 1 39 06 PM

Screen Shot 2023-11-15 at 1 38 01 PM

**Comment by AbhilashKotha** [comment]
@kate-holdener Thanks for finding that, I've fixed it now but I still have some things to fix and I am working on them

1. Handle UI rendering for dual-screen devices like the Surface duo
2. Handle the confirmation popup responsiveness

**Comment by AbhilashKotha** [comment]
@kate-holdener @loganwyas I believe I have got it to a good state now and regarding the devices with two viewports like Surface Duo, I think we need a full sprint to make all of our applications work with such devices. Could you please pull the latest commit and review my PR?

**Review by kate-holdener — APPROVED** [review]
Looks great!

**Pull request merged**
