### PR TITLE
shelter_dashboard

### PR DESCRIPTION
**Pull request by Sai9797**
shelter dashboard wireframe in html

### CODE REVIEW

**Comment by kate-holdener** [comment]
@Sai9797 Thanks for these changes. Please add a screenshot to the pull request (you can edit your original PR comment and add a screenshot there).

**Comment by Sai9797** [comment]
Ok proffesor

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: kate-holdener ***@***.***>
Sent: Friday, September 22, 2023 8:55:09 AM
To: oss-slu/shelter_volunteers ***@***.***>
Cc: Saiteja Gollapalli ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [oss-slu/shelter_volunteers] shelter_dashboard (PR #13)

CAUTION: This email is from an external source. Do not click links or open attachments unless you recognize the sender and know the content is safe. When in doubt, please report the email to SLUAware by clicking on the three dots within your email and choosing Report To SLUAware.

@Sai9797<https://urldefense.com/v3/__https://github.com/Sai9797__;!!K543PA!IrDVL12SGLI5sZhEFiyZtOivJ7B4tk9ctx8kK0rimUdaMaBrHGqgKXCHpkkH_nCm4u9QzJL41dH4z4s8D9Q-9-H0gKecUgUv$> Thanks for these changes. Please add a screenshot to the pull request (you can edit your original PR comment and add a screenshot there).

**Comment by kate-holdener** [comment]
Screen Shot 2023-09-22 at 3 15 20 PM

For the shelter dashboard, I think once the user signs in, they are signed in for a specific shelter (it's a representative from a specific shelter). So you wouldn't see different shelters on the left.

For volunteers, I think the shelter representative will want to see how many volunteers are signed up for different days/shifts, and maybe post how many volunteers are needed for different days.

Total volunteers section is somewhat confusing. I am not understanding what the "requirements" are for the different volunteers and where they would come from. Perhaps a more useful feature would be to have a place where they can see a list of previous volunteers (so that they could contact them, perhaps, to sign up again).

**Comment by Sai9797** [comment]
@kate-holdener , I have updated the dashboard as per your comments. Please review.
image

**Comment by kate-holdener** [comment]
@Sai9797 Here's a very low tech version of what I'm thinking would be a reasonable dashboard for a shelter admin.
image

It has a summary of upcoming dates, with an option to see more details, a view of the current occupancy/volunteers, and an option to contact past volunteers.

**Comment by Sai9797** [comment]
@kate-holdener , I have updated the dashboard as per your comments. Please review.
Screenshot 2023-09-25 131242

**Review by kate-holdener — APPROVED** [review]

**Pull request merged**
