### PR TITLE
Added a cancel feature and a couple of minor UI fixes

### PR DESCRIPTION
**Pull request by jenniferlee20**
Fixes for #45

**What was changed?**

I have implemented a cancel feature to the application, which enables users to successfully cancel a shift if necessary. I have also added some (very) minor UI fixes to the "Your Dashboard" and "Sign Up For Shifts" page:
- I added some bottom padding to the "Impact Created" cards ["Your Dashboard"]
- I added some bottom margin to the paragraph elements for the shelters in the "Shelters looking for Volunteers" column ["Your Dashboard"]
- Changed "Sign up For Shifts" to "Sign Up For Shifts" in the nav bar
- I added a small top margin to the "Radius (miles): [dropdown button]" to make it look less compact ["Sign Up For Shifts"]
- I fixed the spelling of "opportunities" ["Sign Up For Shifts"]

**Why was it changed?**

Using the existing (DELETE /shifts/) API endpoint, the cancel feature was added to give users the option to cancel their upcoming shifts. The user should not be able to cancel past shifts and the user is required to confirm their cancellation to reduce chances of accidental cancels. The minor UI fixes were made to improve the readability, but please feel free to reject these changes, or let me know if you would like me to undo these UI changes. 

**How was it changed?**

To add the cancel feature, I added an event handler that makes a DELETE request to the server to remove a shift identified by shiftCode. If the shift time is still upcoming and the server responds indicating the deletion was successful (response.ok is true), then the data state is updated to remove the canceled shift. This is done by setting the data to a new array that filters out the shift with the shiftCode. This change in state will cause the component to re-render and reflect the change in the UI. This change can be seen in lines 22-49 in Shifts.js and line 75 in ShiftList.js. 

The rest of the UI fixes can be seen in lines 165 + 167 in Shelters.js, line 37 in NavBar.js, and lines 183-210 + 259-262 + 289 in index.css.

### CODE REVIEW

**Comment by kate-holdener** [comment]
@jenniferlee20 Thank you for the pull request. Your changes generally look good. One thing that needs to be changed is: the user shouldn't be able to cancel past shifts. Right. now, when I go to previous shifts screen, I have an option to cancel.
Screen Shot 2023-11-19 at 10 38 08 AM

If you adjust the code in your fork, the pull request should get adjusted automatically.

**Comment by jenniferlee20** [comment]
Sorry for not catching that—I will work on it immediately and adjust the code in my fork as soon as possible.

**Comment by jenniferlee20** [comment]
In the most recent commit, I have made the following changes:

- I added lines 32-33 + 77-83 into ShiftList.js, which now uses a boolean check to make sure the cancel feature only appears for upcoming shifts. I deleted lines 23-27 from Shifts.js, which I originally thought would ensure that past shifts could not get canceled.
- I updated some more UI aspects of dashboard page because the overall page looked a bit squished to the right. Lines 287-289 of index.css cover this change.
- I added more spacing underneath the shift timeframe <p> and lines 216-219 of index.css cover this change.

Please let me know if you see any additional issues with the changes I have made!

**Review by kate-holdener — APPROVED** [review]
That works well. Thank you @jenniferlee20! Welcome to being an open-source contributor!

**Pull request merged**
